### PR TITLE
Implementing Highlights for Sales and Productions

### LINKED ISSUE #36: Implement Highlights for Sales and Productions too
At the moment, we are just highlighting the table on the dashboard if the quantity falls below a certain point (which is a configurable value).

We may also want to highlight if sales and production are below certain values too. So that at the end of the day, if sales or production is low, it can be easily identified.

Technically, it's very simple to do. Just add two more configurable values to the SystemConfiguration table and add conditions in the index views of Sales and Production.

### PR DESCRIPTION
**Pull request by gullariz12**
Loom: https://www.loom.com/share/01523da90a584175b80f79c49a5ca924

### CODE REVIEW

**Review by tannakartikey — CHANGES_REQUESTED** [review]
Let's make system configuration table with keys on one column and value on another. Right now it's the other way around. Difficult to see on mobile.

Let's highlight entries in sales and daily reports too if they are below the thresholds set in the configuration.

Inventory, sales, productions, etc let's include all config.

**Comment by gullariz12** [comment]
@tannakartikey we can add the threshold for the daily sales but how can we detect the threshold for the custom range sales report?
do we have to add the threshold like(7 days, one month etc) and then implement the logic to fetch and implement threshold for selected range? Please share your thoughts on this.

Now we have threshold for the flavor, sales, productions, I will add for the inventory and do we need this threshold for the transfers? e.g(maximum transfers to per store)

**Comment by tannakartikey** [comment]
> @tannakartikey we can add the threshold for the daily sales but how can we detect the threshold for the custom range sales report?
> do we have to add the threshold like(7 days, one month etc) and then implement the logic to fetch and implement threshold for selected range? Please share your thoughts on this.
> 
> Now we have threshold for the flavor, sales, productions, I will add for the inventory and do we need this threshold for the transfers? e.g(maximum transfers to per store)

Yes, my bad. Let's not hilight anything in the custom report. No need to have the threshold for transfer at this time. 

We just need to highlight low sales, low inventory and low productions in daily table and single pages of sales, productions and inventory

**Comment by gullariz12** [comment]
> > @tannakartikey we can add the threshold for the daily sales but how can we detect the threshold for the custom range sales report?
> > do we have to add the threshold like(7 days, one month etc) and then implement the logic to fetch and implement threshold for selected range? Please share your thoughts on this.
> > Now we have threshold for the flavor, sales, productions, I will add for the inventory and do we need this threshold for the transfers? e.g(maximum transfers to per store)
> 
> Yes, my bad. Let's not hilight anything in the custom report. No need to have the threshold for transfer at this time.
> 
> We just need to highlight low sales, low inventory and low productions in daily table and single pages of sales, productions and inventory

Noted, thanks.

**Comment by gullariz12** [comment]
@tannakartikey feedback incorporated please review it at your convenience.

**Review by tannakartikey — APPROVED** [review]

**Pull request merged**
